# =============================================================================
#
# Bayesian Meta-Regression Analysis: Modulation of Carbon Anomalies (Z-Score)
# Expanded Predictors: CH, LAI, MAP, Fpar, MAT, Weighted_AWC, LATITUDE & All Combinations
#
# *** Version: Normal (Gaussian) Distribution - Heatwave (HW) Scenarios ***
#
# Analysis of three scenarios:
# 1. HW_ge_2: H >= 2 (Heatwave)
# 2. HW_ge_2_VPD_lt_2: H >= 2 & VPD < 2 (Pure Heatwave)
# 3. HW_ge_2_VPD_ge_2: H >= 2 & VPD >= 2 (Compound Heatwave & VPD)
#
# Key Features:
# - Dynamic Model Generation: All combinations of predictors (up to 4 vars)
# - Response Variable: mean_zscore (weighted by zscore_se)
# - Saves all brms model objects to .RData
#
# =============================================================================

library(tidyverse)
library(ggplot2)
library(brms)
library(patchwork)
library(posterior)
library(ggpmisc)
library(utils) # for combn

cat("========== Expanded Bayesian Meta-Regression Analysis (Gaussian, HW) ==========\n")
cat("Predictors: CH, LAI, MAP, Fpar, MAT, Weighted_AWC, LATITUDE\n")
cat("Strategy: Running combinations of variables (up to 4)\n\n")

# =============================================================================
# Section 0: Configuration
# =============================================================================
#
# Reviewer-friendly path settings
# --------------------------------
# This script is designed to be run from the root directory of the GitHub
# repository.
#
# Expected repository structure:
#
# Bayesian_Regression_Project/
# ├── Bayesian_anomalies_H_Gaussian_multifactors_v5.R
# ├── data/
# │   ├── All_Sites_ZScore_H_Statistics_Summary.csv
# │   └── Folder_List_All_North.csv
# └── outputs/
#
# Before running this script, please place the two required input files in the
# "data/" folder.
#
# In RStudio, reviewers can do either of the following:
#   1. Open the .Rproj file if provided, then run this script; or
#   2. Manually set the working directory to the repository root before running:
#        setwd("path/to/Bayesian_Regression_Project")
#
# No user-specific absolute paths such as "D:/..." are used below.

# The repository root directory.
# This assumes the script is run from the root folder of the GitHub repository.
project_dir <- getwd()

CONFIG <- list(
  
  # ---------------------------------------------------------------------------
  # Input directory
  # ---------------------------------------------------------------------------
  # All input data files should be placed in the "data" folder inside the
  # GitHub repository.
  #
  # The rest of the script uses:
  #   setwd(CONFIG$base_dir)
  #   read_csv(CONFIG$stats_file)
  #   read_csv(CONFIG$folder_list_file)
  #
  # Therefore, CONFIG$base_dir is set to the data folder so that the existing
  # code below does not need to be changed.
  base_dir = file.path(project_dir, "data"),
  
  # ---------------------------------------------------------------------------
  # Input file names
  # ---------------------------------------------------------------------------
  # These are file names only, not full paths.
  # Reviewers only need to make sure these files are placed in the "data" folder.
  stats_file = "All_Sites_ZScore_H_Statistics_Summary.csv",
  folder_list_file = "Folder_List_All_North.csv",
  
  # ---------------------------------------------------------------------------
  # Output directory
  # ---------------------------------------------------------------------------
  # All results generated by this script will be saved in the "outputs" folder.
  # The folder will be created automatically if it does not already exist.
  output_dir = file.path(
    project_dir,
    "outputs",
    "Gaussian_Arbitrary_Combinations_North_With_LAT_v2"
  ),
  
  # ---------------------------------------------------------------------------
  # Heatwave scenarios used in the Bayesian meta-regression
  # ---------------------------------------------------------------------------
  # name  : scenario name used in the input statistics file
  # label : label used in figures and result tables
  # color : color used for plotting
  scenarios = list(
    list(
      name = "HW_ge_2",
      label = "H >= 2",
      color = "#984EA3"
    ),
    list(
      name = "HW_ge_2_VPD_lt_2",
      label = "H >= 2 & VPD < 2",
      color = "#FF7F00"
    ),
    list(
      name = "HW_ge_2_VPD_ge_2",
      label = "H >= 2 & VPD >= 2",
      color = "#4DAF4A"
    )
  ),
  
  # ---------------------------------------------------------------------------
  # Minimum sample size
  # ---------------------------------------------------------------------------
  # Sites with fewer than this number of observations will be excluded.
  min_sample_size = 15,
  
  # ---------------------------------------------------------------------------
  # Model configuration
  # ---------------------------------------------------------------------------
  # The script will fit all predictor combinations up to this number of
  # predictors per model.
  #
  # For example, if max_vars_per_model = 4, the script will evaluate all
  # one-variable, two-variable, three-variable, and four-variable models.
  max_vars_per_model = 4,
  
  # ---------------------------------------------------------------------------
  # Output file prefix
  # ---------------------------------------------------------------------------
  # This prefix will be used when saving tables, figures, and model objects.
  output_prefix = "AllCombos_H_ZScore_Gaussian_WithLAT"
)

# ---------------------------------------------------------------------------
# Set working directory and create output folder
# ---------------------------------------------------------------------------
# The following lines are kept compatible with the original script.
# Since CONFIG$base_dir points to the "data" folder, the later read_csv()
# commands can continue to use file names only.
setwd(CONFIG$base_dir)

# Create output directory if it does not already exist.
if (!dir.exists(CONFIG$output_dir)) {
  dir.create(CONFIG$output_dir, recursive = TRUE)
}

# =============================================================================
# Section 1: Data Preparation
# =============================================================================

cat("--- 1. Data Loading and Preparation ---\n")
all_stats <- read_csv(CONFIG$stats_file, show_col_types = FALSE)
folder_list <- read_csv(CONFIG$folder_list_file, show_col_types = FALSE)

# 检查所有需要的列是否存在 (注意：这里加入了 LATITUDE)
required_cols <- c("canopy_height", "Mean_Annual_Precip", "Growing_LAI", "Fpar", "MAT", "Weighted_AWC", "LATITUDE")
missing_cols <- required_cols[!required_cols %in% names(folder_list)]
if(length(missing_cols) > 0) stop(paste("Error: Columns missing in folder_list:", paste(missing_cols, collapse=", ")))

# 整理站点元数据
site_info <- folder_list %>%
  mutate(
    clean_name = sub("_\\d{4}_\\d{4}$", "", folder),
    country_code = substr(clean_name, 1, 2),
    site_part = sub("^[A-Z]{2}_", "", clean_name),
    site_code = paste0(country_code, "-", site_part)
  ) %>%
  select(site_code, IGBP, 
         CH = canopy_height, 
         MAP = Mean_Annual_Precip,
         LAI = Growing_LAI,
         Fpar = Fpar,
         MAT = MAT,
         AWC = Weighted_AWC,
         LAT = LATITUDE) # <--- 读取 LATITUDE 并重命名为 LAT

cat("✓ Site metadata loaded successfully (Included LATITUDE).\n\n")

# =============================================================================
# Section 2: Prepare Data for Each Scenario
# =============================================================================

cat("--- 2. Preparing Data for Each Scenario ---\n")
all_scenario_data <- list()

for (i in seq_along(CONFIG$scenarios)) {
  scenario_info <- CONFIG$scenarios[[i]]
  scenario_name <- scenario_info$name
  
  response_data <- all_stats %>%
    filter(scenario == scenario_name) %>%
    rename(beta_hw = mean_zscore, se_beta = zscore_se) %>%
    select(site_code, beta_hw, se_beta, n, p_value)
  
  meta_data <- response_data %>%
    left_join(site_info, by = "site_code") %>%
    filter(
      n >= CONFIG$min_sample_size,
      !is.na(beta_hw), !is.na(se_beta), se_beta > 0,
      !is.na(IGBP),
      !is.na(CH), !is.na(MAP), !is.na(LAI), !is.na(Fpar), !is.na(MAT), !is.na(AWC), !is.na(LAT) # <--- Check LAT
    )
  
  if (nrow(meta_data) > 10) {
    # 标准化所有预测变量
    meta_data <- meta_data %>%
      mutate(
        CH_std   = as.numeric(scale(CH)),
        MAP_std  = as.numeric(scale(MAP)),
        LAI_std  = as.numeric(scale(LAI)),
        Fpar_std = as.numeric(scale(Fpar)),
        MAT_std  = as.numeric(scale(MAT)),
        AWC_std  = as.numeric(scale(AWC)),
        LAT_std  = as.numeric(scale(LAT)), # <--- Standardize LAT
        scenario = scenario_name,
        scenario_label = scenario_info$label
      )
    all_scenario_data[[scenario_name]] <- meta_data
    cat("  Scenario:", scenario_info$label, "-> N =", nrow(meta_data), "sites (Complete Cases)\n")
  } else {
    cat("  Scenario:", scenario_info$label, "-> Skipped (Insufficient data)\n")
  }
}
cat("\n")

# =============================================================================
# Section 3: Generate Dynamic Model Configurations
# =============================================================================

cat("--- 3. Generating Model Combinations ---\n")

# <--- Added LAT_std to the pool
predictors_pool <- c("CH_std", "MAP_std", "LAI_std", "Fpar_std", "MAT_std", "AWC_std", "LAT_std")

model_configs <- list()
model_counter <- 1

# 生成 1 到 4 个变量的所有组合
for (k in 1:CONFIG$max_vars_per_model) {
  combos <- combn(predictors_pool, k, simplify = FALSE)
  
  for (combo in combos) {
    formula_str <- paste(combo, collapse = " + ")
    label_parts <- gsub("_std", "", combo)
    label_str <- paste(label_parts, collapse = "+")
    
    model_configs[[model_counter]] <- list(
      id = paste0("M", model_counter),
      formula = formula_str,
      label = label_str,
      vars = combo 
    )
    model_counter <- model_counter + 1
  }
}

cat(paste0("Total models generated per scenario: ", length(model_configs), "\n"))
cat("Example models:\n")
print(head(model_configs, 3))
cat("...\n\n")

# =============================================================================
# Section 4: Define Models & Bayesian Fit
# =============================================================================

cat("--- 4. Running Bayesian Models (Gaussian) ---\n")

priors_gaussian <- c(
  prior(normal(0, 1), class = Intercept),
  prior(normal(0, 1), class = b),
  prior(exponential(1), class = sigma)
)

results_summary <- data.frame()
all_models_objects <- list() 

all_possible_vars <- predictors_pool

for (scenario_name in names(all_scenario_data)) {
  meta_data <- all_scenario_data[[scenario_name]]
  scenario_label <- meta_data$scenario_label[1]
  
  cat(paste0(">>> Processing Scenario: ", scenario_label, " <<<\n"))
  
  scenario_models <- list()
  
  # 遍历所有模型组合
  for (cfg in model_configs) {
    # 简单的进度显示 (每10个模型打一个点)
    if(as.numeric(sub("M","",cfg$id)) %% 10 == 0) cat(".")
    
    f <- as.formula(paste("beta_hw | se(se_beta, sigma = TRUE) ~", cfg$formula))
    
    fit <- brm(
      formula = f,
      data = meta_data,
      family = gaussian(),
      prior = priors_gaussian,
      iter = 4000, warmup = 1000, chains = 4, cores = 4, seed = 123,
      control = list(adapt_delta = 0.99, max_treedepth = 12),
      silent = 2, refresh = 0
    )
    
    # 【保存模型对象】
    scenario_models[[cfg$id]] <- fit 
    
    post <- as_draws_df(fit)
    
    row_res <- data.frame(
      Scenario = scenario_label,
      Model_ID = cfg$id,
      Model_Formula = cfg$formula,
      Model_Label = cfg$label,
      N_sites = nrow(meta_data),
      Sigma = mean(post$sigma),
      Num_Vars = length(cfg$vars)
    )
    
    for(v in all_possible_vars) {
      col_name <- paste0("b_", v)
      if(col_name %in% names(post)) {
        samples <- post[[col_name]]
        row_res[[paste0("Beta_", v)]] <- mean(samples)
        row_res[[paste0("Low_", v)]]  <- quantile(samples, 0.025)
        row_res[[paste0("Up_", v)]]   <- quantile(samples, 0.975)
        row_res[[paste0("Prob_Neg_", v)]] <- mean(samples < 0)
        row_res[[paste0("Prob_Pos_", v)]] <- mean(samples > 0)
      } else {
        row_res[[paste0("Beta_", v)]] <- NA
        row_res[[paste0("Low_", v)]]  <- NA
        row_res[[paste0("Up_", v)]]   <- NA
        row_res[[paste0("Prob_Neg_", v)]] <- NA
        row_res[[paste0("Prob_Pos_", v)]] <- NA
      }
    }
    
    results_summary <- bind_rows(results_summary, row_res)
  }
  cat(" Done.\n")
  
  # 【保存该情景下的所有模型列表】
  all_models_objects[[scenario_name]] <- scenario_models 
  cat("\n")
}

out_csv <- file.path(CONFIG$output_dir, paste0(CONFIG$output_prefix, "_results_summary.csv"))
write_csv(results_summary, out_csv)
cat("✓ Detailed results summary saved to:", out_csv, "\n\n")

# =============================================================================
# Section 6: Visualization
# =============================================================================

cat("--- 6. Creating Visualizations ---\n")

cat("Generating scatter plots for all predictors...\n")

variables_to_plot <- list(
  list(col = "CH",   label = "Canopy Height (m)"),
  list(col = "LAI",  label = "Growing LAI"),
  list(col = "MAP",  label = "MAP (mm)"),
  list(col = "Fpar", label = "Fpar"),
  list(col = "MAT",  label = "MAT (°C)"),
  list(col = "AWC",  label = "Weighted AWC"),
  list(col = "LAT",  label = "Latitude (°)") # <--- Added LAT Plot
)

for (v in variables_to_plot) {
  var_col <- v$col
  var_lab <- v$label
  
  plots_list <- list()
  
  for (scenario_name in names(all_scenario_data)) {
    meta_data <- all_scenario_data[[scenario_name]]
    scenario_label <- meta_data$scenario_label[1]
    
    p <- ggplot(meta_data, aes(x = .data[[var_col]], y = beta_hw)) +
      geom_point(aes(color = IGBP), alpha = 0.7, size = 2) +
      geom_smooth(method = "lm", color = "black", linetype = "dashed", se=TRUE) +
      stat_poly_eq(formula = y ~ x, 
                   aes(label = paste(..eq.label.., ..rr.label.., ..p.value.label.., sep = "*\", \"*")), 
                   parse = TRUE, size = 3, label.x = "left", label.y = "top") +
      labs(title = paste0(scenario_label), x = var_lab, y = "Mean Z-Score") +
      theme_minimal() +
      theme(legend.position = "none", plot.title = element_text(size = 10))
    
    plots_list[[scenario_name]] <- p
  }
  
  final_p <- wrap_plots(plots_list, ncol = 3) + 
    plot_layout(guides = "collect") & theme(legend.position = "bottom")
  
  ggsave(file.path(CONFIG$output_dir, paste0(CONFIG$output_prefix, "_Scatter_", var_col, ".png")), 
         final_p, width = 12, height = 4.5, dpi = 300)
}

cat("Generating Forest Plot for Univariate Models...\n")

forest_data <- results_summary %>%
  filter(Num_Vars == 1) %>% 
  select(Scenario, Model_Label, matches("Beta_|Low_|Up_")) %>%
  pivot_longer(
    cols = matches("Beta_|Low_|Up_"),
    names_to = c("Stat", "Var"),
    names_pattern = "(Beta|Low|Up)_(.*)",
    values_to = "value"
  ) %>%
  filter(!is.na(value)) %>% 
  pivot_wider(names_from = Stat, values_from = value) %>%
  mutate(Var = gsub("_std", "", Var))

p_forest <- ggplot(forest_data, aes(x = Beta, y = Var, color = Scenario)) +
  geom_vline(xintercept = 0, linetype = "dashed", color = "gray60") +
  geom_point(position = position_dodge(width = 0.5), size = 3) +
  geom_errorbarh(aes(xmin = Low, xmax = Up),
                 position = position_dodge(width = 0.5), height = 0.2) +
  labs( 
    x = "Posterior mean standardized effect (β)", y = "Control") +
  theme_minimal() +
  scale_color_manual(values = c("#984EA3", "#FF7F00", "#4DAF4A"))

ggsave(file.path(CONFIG$output_dir, paste0(CONFIG$output_prefix, "_Forest_Univariate.png")), 
       p_forest, width = 8, height = 6, dpi = 300)

cat("✓ Visualization complete.\n")

# =============================================================================
# Section 7: Save R Workspace
# =============================================================================

cat("\n--- 7. Saving R Workspace ---\n")
workspace_file <- file.path(CONFIG$output_dir, paste0(CONFIG$output_prefix, "_workspace.RData"))
save(results_summary, all_scenario_data, all_models_objects, file = workspace_file)
cat("✓ Workspace saved (Including all model objects).\n")

cat("========== Analysis Complete ==========\n")
